name: build-windows-installer
on: 
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps: 
        - uses: actions/checkout@v2
        - name: Set up Python 3.x
          uses: actions/setup-python@v2
          with: 
            python-version: '3.9'
        - name: PyInstaller Windows
          uses: JackMcKew/pyinstaller-action-windows@main
          with:
            path: src
        - uses: actions/upload-artifact@v2
          with:
            name: HelloWorld
            path: src/dist/windows
        - uses: actions/upload-artifact@v2
          with:
            name: warn-HelloWorld.txt
            path: tmp\HelloWorld\warn-HelloWorld.txt